name: Hello World 

on: 
  workflow_dispatch:

jobs:
  github:
    name: github-actions
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        # This step checks out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Echo Hello World
        run: | 
          echo "Hello World!!"
          sleep 10
          echo "bye world!!"

