name: Hello World 

on: 
  schedule:
    - cron: '* 9 5 * *' #9:00 AM on the 5th day of every month.
    - cron: '* 9 * * 3' # 9:00 AM every Wednesday.
    - cron: '0 9 */2 * *' # 9:00 AM every alternate day.
    - cron: '* * * * *'  #by default it'll run every 5 mins
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter  name'
        required: true
jobs:
  github:
    name: github-actions
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        # This step checks out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Echo Trigger Message
        run: echo "Triggered by user ${{ github.event.inputs.name }}"



