name: Hello World 

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
jobs:
  github:
    name: github-actions
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        # This step checks out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Echo Trigger Message
        run: echo "Triggered by ${{ github.event.inputs.name }}"



