
name: Hello World Workflow

on: 
  workflow_dispatch:

jobs:
  super-lint:
    name: Lint code base
    runs-on: ${{ fromJSON('["ubuntu-latest"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - uses: actions/checkout@v2
      # This step checks out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Echo Hello World
        run: echo "Hello World!!"
      # This step echoes "Hello World!!" in the log
